version: '3.7'

services: 

  nginx:
    build: ./nginx
    volumes: 
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8080:80
    depends_on: 
      - web

  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn smallTalk.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes: 
      - static_volume:/home/app/web/staticfiles
    environment: 
      - DEBUG=0
      - SECRET_KEY=foo
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=hello_django_dev
      - SQL_USER=hello_django
      - SQL_PASSWORD=hello_django
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
    depends_on: 
      - db

  asgi_web:
    build: .
    command: gunicorn smallTalk.asgi:application -w 1 -k uvicorn.workers.UvicornWorker -b :9001
    volumes: 
      - static_volume:/home/app/web/staticfiles
    links:
      - redis
    ports: 
      - "9001:9001"
    environment: 
      - DEBUG=0
      - SECRET_KEY=foo
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=hello_django_dev
      - SQL_USER=hello_django
      - SQL_PASSWORD=hello_django
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
    depends_on: 
      - redis
      - db

  db:
    image: postgres:13.0-alpine
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    environment: 
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data:
  static_volume:
