global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: django
    metrics_path: /metrics
    static_configs:
      - targets:
        - 'web:8000'